### ISSUE TITLE
Error: cannot coerce type 'closure' to vector of type 'integer'

### ISSUE THREAD

**Issue by tnt0932** [marcusvolz/strava#12]
After going through the initial setup, when I run `data <- process_data("/Users/xyz/activites/20121025-011125-Run.gpx")` in the R Console gui I get:
```Error in mutate_impl(.data, dots) : 
  Evaluation error: cannot coerce type 'closure' to vector of type 'integer'.
```

Any ideas how to resolve this? This is my first foray into R, so apologies if I'm making a basic error.

**Comment by marcusvolz** [comment]
Hi Troy, I've not come across that error message before - if you're happy to send me the gpx file I can investigate further.

**Comment by tnt0932** [comment]
Thanks Marcus. Here's a .zip with the file: [20121024-011124-Run.gpx.zip](https://github.com/marcusvolz/strava/files/1849714/20121024-011124-Run.gpx.zip)

**Comment by marcusvolz** [comment]
Seems to be working for me. One thing you might try is to update to the latest version of R if you haven't already.

![facets001](https://user-images.githubusercontent.com/12025275/37937254-a49546f6-31a4-11e8-9de9-b5decf1e92e4.png)
![elevations001](https://user-images.githubusercontent.com/12025275/37937255-a4c2cafe-31a4-11e8-8642-1f63b36418f8.png)

**Comment by marcusvolz** [comment]
Actually I see the problem - just drop the name of the gpx file - you only want to point it to the directory containing all the gpx files, i.e. process_data("/Users/xyz/activites")

**Comment by tnt0932** [comment]
That's it (and I misspelled `activites`)! Thanks for the help with that. It's a great project 👍

**Comment by marcusvolz** [comment]
Nice, glad it works!

**Comment by bibekg** [comment]
Just ran into this too, might be a good idea to update the main `README.md` to say to point `process_data` at the directory rather than a specific gpx file. Thanks for the awesome library!

**Comment by mihagazvoda** [comment]
@bibekg Thanks, just created a pull request.
