### ISSUE TITLE
Error: arguments imply differing number of rows

### ISSUE THREAD

**Issue by MayaGans** [marcusvolz/strava#15]
Hi! I'm trying to load in Strava data and I get the following error when trying to run the `process_data` function: 

`Error in data.frame(lat = lat, lon = lon, ele = ele, time = time, id = id) : arguments imply differing number of rows: 1366, 0, 1`

I'm not familiar with the structure of .gpx files so I was hoping you could shed some insight? 

Thank you!

**Comment by marcusvolz** [comment]
Hi Maya, I fixed an issue with process_data yesterday, so try updating to the latest package. Then in your current working directory create a sub-directory called "data" and put all the gpx files in there, then execute process_data("data").

**Comment by MayaGans** [comment]
Hi @marcusvolz thanks for getting back to me so quickly! I did as you said and now get the error `Error in mutate_impl(.data, dots) : Column `id` must be length 0 (the number of rows) or one, not 3` 

Any ideas?

**Comment by marcusvolz** [comment]
It looks like it is trying to process three files but is returning empty data for each file. I'm not sure that I can be of much help without seeing the gpx files. I noticed Strava no longer allows bulk export of gpx files, so maybe your files are in a different format that process_data isn't set up for. The only other thing I can suggest is upgrading to the latest version of R if you haven't already.

**Comment by hugovk** [comment]
I also saw the first error.

When you upload to Strava, they make "corrections" on the file, for example to try and fix rogue elevation data.

Pre-GPDR, you could [bulk export all your activities as GPX files](https://web.archive.org/web/20170322015958/https://support.strava.com/hc/en-us/articles/216918437-Exporting-your-Data-and-Bulk-Export#Bulk), I think these were the corrected ones.

These visualisation tools were fine with them, maybe Strava standardised them.

Post-GDPR, you can [export an archive of your account](https://support.strava.com/hc/en-us/articles/216918437-Exporting-your-Data-and-Bulk-Export#Bulk) which includes much more data, however your activities are now in their _original_ file format. For me, that was GPX for GPX files I uploaded from another service, and from the Strava Android app, and FIT format from my Wahoo GPS tracker.

These tools were fine with the GPX files. I tried converting the FIT files to GPX using [GPSBabel](https://www.gpsbabel.org), and also [FIT-to-GPX](http://regex.info/blog/2017-05-13/2799), but these tools gave `Error in data.frame` for them. In the end, I [exported those activities](https://support.strava.com/hc/en-us/articles/216918437-Exporting-your-Data-and-Bulk-Export#GPX) from the Strava website (here's a [script to download several](https://github.com/hugovk/strava-tools/blob/master/download_fit_as_gpx.py)).

I think Strava should probably still be offering the corrected tracks under GDPR.

I'll retest the with the latest version of this package.

**Comment by hugovk** [comment]
macOS High Sierra 10.13
R 3.5.1
Latest version of this package: b98010aa
devtools 1.13.6
mapproj 1.2.6
tidyverse 1.2.1

Here's a test using a FIT file converted to GPX using:
* GPSBabel
* FIT-to-GPX
* Strava export

[testing.zip](https://github.com/marcusvolz/strava/files/2386585/testing.zip) contains the input FIT file, the three GPX files, and the output plots. 

```r
$ R

R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.6.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(strava)
> library(tidyverse)
── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──
✔ ggplot2 3.0.0     ✔ purrr   0.2.5
✔ tibble  1.4.2     ✔ dplyr   0.7.6
✔ tidyr   0.8.1     ✔ stringr 1.3.1
✔ readr   1.1.1     ✔ forcats 0.3.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

> data <- process_data("fit2gpx")
Error in data.frame(lat = lat, lon = lon, ele = ele, time = time, type = type) :
  arguments imply differing number of rows: 10754, 10715, 1

> data <- process_data("gpsbabel")
Error in data.frame(lat = lat, lon = lon, ele = ele, time = time, type = type) :
  arguments imply differing number of rows: 10754, 10715, 1

> data <- process_data("strava-export")
> p1 <- plot_facets(data)
> ggsave("plots/facets-strava-export.png", p1, width = 20, height = 20, units = "cm")
> p2 <- plot_map(data, lon_min = 22.65, lon_max = 26.65, lat_min = 59.61, lat_max = 60.84) # Uusimaa
> ggsave("plots/map-strava-export.png", p2, width = 20, height = 15, units = "cm", dpi = 600)
> p3 <- plot_elevations(data)
> ggsave("plots/elevations-strava-export.png", p3, width = 20, height = 20, units = "cm")
>
```

Both the problem files have 10754 `<trkpt>`s (the good one has 10787).

**Comment by MayaGans** [comment]
Thanks for the tips FTR you can still bulk download GPX files under `Settings > My Account > Get Started > Download Request` but it's unfortunately still not working. I ran @hugovk's code with the test file and that did work... :/

I've attached one of my GPX files, I have ZERO familiarity with their structure, would you mind taking a peek to see if they're in the correct format? The extension is .gpx but maybe I need to convert them? 

[1969459350.gpx.gz](https://github.com/marcusvolz/strava/files/2386926/1969459350.gpx.gz)

Thanks again!!

**Comment by MayaGans** [comment]
I really just wanted to generate the small multiple plots, by taking out the ele = ele argument within the plot dist function I was able to do so -- THANK YOU!

**Comment by hugovk** [comment]
Correcting myself, when I said:

> * The working one has `lat`, `lon`, `ele` (elevation) and `time`.
> * The non-working ones only have `lat`, `lon` and `time`.

My two converted files *do* have some `ele` values, but not every track point has one. There are 10754 points (with `lat`, `lon`, `time`), and only 10715 of those have `ele` values. Maya's file has 1366 points with 0 `ele` values. We can see these pairs of numbers in the error messages:

```r
Error in data.frame(lat = lat, lon = lon, ele = ele, time = time, type = type) :
  arguments imply differing number of rows: 10754, 10715, 1
```

Strava makes altitude corrections, that'll be why their exports all have points with elevation values but some original files do not.
