### ISSUE TITLE
What to do with new export format?

### ISSUE THREAD

**Issue by basilesimon** [marcusvolz/strava#19]
Hi there,

It seems like the Strava archive (or mine, at least) doesn't include GPX any more, but rather `.tcx.gz` and `.fit.gz` files.

However this package only includes support for GPX, [as per this line](https://github.com/marcusvolz/strava/blob/master/R/process_data.R#L52)

I believe I've heard about a change in their takeout format in May 2018 – do you know if that's changed as well?

Edit:
[seems like this is a documented issue Strava is not engaging with...](https://support.strava.com/hc/en-us/community/posts/360014914631-Activities-in-the-new-bulk-export-feature-have-meaningless-names-and-multiple-formats-)

Edit 2: 
[seems like you recommend scraping to go around this issue...](https://github.com/hugovk/strava-tools/blob/master/download_fit_as_gpx.py)

**Comment by hugovk** [comment]
Here's some notes I made when converting things earlier: 

https://github.com/hugovk/strava-tools

I think, under GDPR, that Strava still have to provide our data to us. Not just the original data we uploaded, but also any processed data they have made (like track altitude and course adjustments) and in a usable format (eg. GPX).

**Comment by basilesimon** [comment]
I see, I see. Most interesting development – well done and thank you on `strava-tools`!
