### ISSUE TITLE
Doesn't build with R-4.1.0

### ISSUE THREAD

**Issue by datawookie** [marcusvolz/strava#32]
Hi!

Just letting you know that this packages doesn't install due to the `ggTimeSeries` package being removed from CRAN. It's still available from GitHub. Just noticed this when installing on a fresh system. Still works on my old system though, which already has `ggTimeSeries`.

Thanks, Andrew.

**Comment by marcusvolz** [comment]
Thanks for this, Andrew. I've removed ggTimeSeries from the package DESCRIPTION and added a note to the README to indicate that users will have to manually install ggTimeSeries from github.

**Comment by datawookie** [comment]
Great! Thank you.
