### ISSUE TITLE
Add hacktoberfest topic

### ISSUE THREAD

**Issue by datawookie** [marcusvolz/strava#34]
Hi @marcusvolz, I've just tried to add the `hacktoberfest` topic to the repository but I don't appear to have permissions. Could you please either add it or grant me the required permissions? Thanks, Andrew.

**Comment by hugovk** [comment]
It's already there :)

![image](https://user-images.githubusercontent.com/1324225/136185999-560492f1-b38c-4060-ba64-7552b395e8b6.png)

https://github.com/marcusvolz/strava

**Comment by marcusvolz** [comment]
Hi @datawookie, as @hugovk pointed out the topic has already been added. Looks like "collaborator" is the only permission level I am able to grant for a user account repository such as this, which unfortunately does not allow topic management - see https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-user-account-settings/permission-levels-for-a-user-account-repository

**Comment by datawookie** [comment]
@datawookie walks away, hanging his head in shame.
