### ISSUE TITLE
"Squashed" maps

### ISSUE THREAD

**Issue by hugovk** [marcusvolz/strava#5]
My maps look great, but also a bit squashed. If I plot it with Helsinki's bounding box:
```
p2a <- plot_map(data, lon_min = 24.8312, lon_max = 25.2022, lat_min = 60.1301, lat_max = 60.2893)
```
I get a map like this:

![map001](https://user-images.githubusercontent.com/1324225/34416653-20429c38-ebfd-11e7-802a-dee2db96764c.png)

When it normally looks more like this:

![image](https://user-images.githubusercontent.com/1324225/34418382-7d82d634-ec06-11e7-898b-e0f00cc5b65b.png)

http://maps.stamen.com/#toner/11/60.1934/25.0715

Do you know what accounts for this, and how I could square it off? Thanks!

**Comment by marcusvolz** [comment]
That's strange, the addition of coord_equal() should provide the true aspect ratio. Could you provide your data?

**Comment by hugovk** [comment]
Here's a single coastal route: [20130902-171543-Ride.gpx.zip](https://github.com/marcusvolz/strava/files/1592878/20130902-171543-Ride.gpx.zip)


On Strava it looks like this:

![image](https://user-images.githubusercontent.com/1324225/34434174-f925cefa-ec8c-11e7-8b33-6aad3fd747c3.png)


```R
> data <- process_data('.')
> p1 <- plot_facets(data)
> ggsave("plots/facets003.png", p1, width = 20, height = 20, units = "cm")
> p2a <- plot_map(data, lon_min = 24.8312, lon_max = 25.2022, lat_min = 60.1301, lat_max = 60.2893)
> ggsave("plots/map003.png", p2a, width = 20, height = 20, units = "cm", dpi = 600)
```

Which produces this facet:

![facets003](https://user-images.githubusercontent.com/1324225/34434224-3587e9dc-ec8d-11e7-8549-ef5981e3a484.png)


But this map:

![image](https://user-images.githubusercontent.com/1324225/34434162-d72620c0-ec8c-11e7-95ae-00fd55adc2cd.png)

**Comment by marcusvolz** [comment]
The facet uses scales = "free" and doesn't use coord_equal, so it will scale to fill out the facet. The map uses coord_equal, so the x and y axes have the same relative scale (i.e. one unit on the x-axis is the same length as one unit on the y-axis).

From the raw data it looks like the ranges are [60.14653. 60.16568] and [24.920093, 24.961935], so it looks like the map is being plotted correctly - maybe the data has been corrupted?

As a temp solution you can just remove coord_equal from the map code and then manually resize the plot in RStudio before saving.

**Comment by hugovk** [comment]
Of course, the reason is the earth is a sphere and flat maps are projections. At the equator one degree of lat/lon are roughly equal. As we go further north, one degree of latitude gets to zero. At 60N, we're 2/3 up. 

So we probably want to scale the latitude by how far away from the equator we are.

**Comment by hugovk** [comment]
It's as easy as using `ggplot2::coord_map()` instead of `ggplot2::coord_equal()` to fix it!

![image](https://user-images.githubusercontent.com/1324225/34446089-25ffc9c2-ece1-11e7-89cd-551b08e0db4d.png)

**Comment by marcusvolz** [comment]
Thanks for figuring this out. It makes sense, Helsinki is further from the equator than Melbourne which is why my one didn't seem to be particularly distorted.
