### ISSUE TITLE
process_data() Ignores the Time Zone in the GPX File

### ISSUE THREAD

**Issue by RyanRosario** [marcusvolz/strava#8]
I'll see if I can find a fix for this, but I am notoriously bad at dealing with dates/times in any language. 

My data dump encodes all dates and times in Zulu time (UTC), but based on the code, it treats the dates/times as in PST/PDT. 

In the line I highlighted below, it should somehow read the time zone information that is in the file and encode it as an R date/time in that timezone as well.

https://github.com/marcusvolz/strava/blob/e779084345023dd77f370a2f69f354fadd94490d/R/process_data.R#L34

Example:
The time in one of my files is written as `2016-08-02T23:11:44Z` (Zulu time).
The resulting data frame lists the same date/time as `"2016-08-02 23:11:44 PDT"` (PDT)
To be correct, it should be Zulu. Then all other R time/date manipulations or lubridate will work correctly.

(It's possible that the author's device recorded the times in local time and thus did not encounter this issue)

**Comment by billyangers** [comment]
Changing it like this seems to do the trick:

`time = as.POSIXct(.$time, tz = "GMT", format = "%Y-%m-%dT%H:%M:%OS")) %>%`

**Comment by marcusvolz** [comment]
Thanks Billy, that appears to have worked - there is a separate issue for the calendar plot.
