### ISSUE TITLE
lat/lon reversed, making cumdist incorrect

### ISSUE THREAD

**Issue by jimcremer** [marcusvolz/strava#9]
Nice project.  I have been playing with it and colorizing facets by cumulative time or distance.  I believe the cumulative distances are incorrect because this line in process_data.R

dplyr::mutate(dist_to_prev = c(0, sp::spDists(x = as.matrix(.[, 1:2]), longlat = TRUE, segments = TRUE)),

puts  lat/lon in the wrong order for npDists function. npDists expects lons first.  
I'm am an experienced program but never used R before trying this code.  For me, distances are correct after changing frame line to 
result <- data.frame(lon = lon, lat = lat, ele = ele, time = time)

**Comment by marcusvolz** [comment]
You are correct, thanks for picking this up - To be safe it now uses as.matrix(.[, c("lon", "lat")])
